server:
  port: 9999

restaurante:
  url: http://localhost:8083

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
      - id: pagamentos
        uri: http://localhost:8081
        predicates:
        - Path=/pagamentos/**
      - id: distancia
        uri: lb://distancia
        predicates:
        - Path=/distancias/**
      - id: restaurantes
        uri: http://localhost:8083
        predicates:
        - Path=/restaurantes/**
      - id: monolito
        uri: lb://monolito
        predicates:
        - Path=/**

ribbon:
  eureka: 
    client:
      serviceUrl:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

